pom.xml
=> Fix: Commons FileUpload 및 Tomcat WAS 취약점 조치

src/main/java/egovframework/let/uat/esm/service/EgovSiteManagerService.java, src/main/java/egovframework/let/uat/esm/service/impl/EgovSiteManagerServiceImpl.java, src/main/java/egovframework/let/uat/esm/service/impl/SiteManagerDAO.java, src/main/java/egovframework/let/uat/esm/web/EgovSiteManagerApiController.java, src/main/resources/egovframework/mapper/let/uat/esm/EgovSiteMgr_SQL_altibase.xml, src/main/resources/egovframework/mapper/let/uat/esm/EgovSiteMgr_SQL_cubrid.xml, src/main/resources/egovframework/mapper/let/uat/esm/EgovSiteMgr_SQL_hsql.xml, src/main/resources/egovframework/mapper/let/uat/esm/EgovSiteMgr_SQL_mysql.xml, src/main/resources/egovframework/mapper/let/uat/esm/EgovSiteMgr_SQL_oracle.xml, src/main/resources/egovframework/mapper/let/uat/esm/EgovSiteMgr_SQL_tibero.xml
- 심플홈페이지를 설치 후 로그인 및 사이트관리 메뉴 사용 시 로그인 암호 변경도 화면에서 처리하면 좋겠다는 의도 입니다.
- 추가한 기능은 모두 egovframework.let.uat.esm 신규 패키지에 별도로 모아 놓았다.
- 참고로 esm는 EgovSiteManager 전자정부 사이트 매니저 약자이다.
- EgovSiteManagerApiController 추가 : 사이트관리자의 기존 비번과 비교하여 변경된 비밀번호를 저장하는 메서드 구현.
- EgovSiteManagerService 추가 : 사이트관리자의 로그인 비밀번호를 변경 처리하는 비즈니스 구현 인터페이스.
- EgovSiteManagerServiceImpl 추가: 사이트관리자의 로그인 비밀번호를 변경 처리하는 비즈니스 구현 클래스.
- SiteManagerDAO.java 추가 : 사이트관리자의 로그인 비밀번호를 변경 처리하는 데이터 액세스 클래스.
- EgovSiteMgr_SQL_hsql.xml 추가 : src\main\resources\egovframework\mapper\let\uat\esm 신규 폴더에 나머지 DB별 파일도 추가.
테스트를 완료하셨으면 다음 항목에 [대문자X]로 표시해 주세요. When you're done …
=> 사이트관리자의 비밀번호를 변경하는 API를 egovframework.let.uat.esm 패키지로 신규 생성 후 소스를 추가.

pom.xml, src/main/resources/application.properties, src/test/java/egovframework/study/jpa/domain/Locker.java, src/test/java/egovframework/study/jpa/domain/Member.java, src/test/java/egovframework/study/jpa/domain/Team.java, src/test/java/egovframework/study/jpaTest.java
JPA(Java Persistence API)는 Java 언어 기반의 ORM(Object-Relational Mapping) 기술을 위한 API입니다. ORM은 객체와 관계형 데이터베이스 사이의 매핑을 자동으로 처리해주어 개발자가 SQL 쿼리를 직접 작성하지 않아도 객체를 데이터베이스에 저장하고 조회할 수 있게 해줍니다.
JPA는 이러한 ORM을 위한 인터페이스를 제공하며, 객체지향적인 방식으로 데이터를 다루기 위한 다양한 기능을 제공합니다. JPA를 사용하면 객체를 데이터베이스에 저장하거나 조회하는 일련의 작업들을 간단하게 처리할 수 있으며, 객체간의 연관관계도 쉽게 다룰 수 있습니다.
또한 JPA는 벤더 독립성을 제공하므로, 개발자는 데이터베이스 벤더에 종속되지 않고 표준화된 방식으로 개발을 할 수 있습니다. 이러한 장점들로 인해 JPA는 현재 많은 자바 기반 프로젝트에서 널리 사용되고 있습니다.
- DATABASE/all_sht_data_altibase.sql,all_sht_data_oracle.sql,all_sht_data_mysql.sql....와 같은 데이터베이스별로 SQL을 관리하지 않아도 된다.
- 데이터베이스에 종속되지 않아 운영중인 시스템의 디비를 교체 할 수 있다.
- 객체지향적으로 설계하고 개발하여도 막상 SQL을 작성하다보면 SQL중심, 데이터중심 아키텍처가 될 수 있음 그러나 JPA는 객체지향 프로그래밍을 가능하게 …
=> spring-boot-starter-data-jpa 추가 및 JPA 학습 테스트 코드 작성

README.md, pom.xml, src/main/resources/application-dev.properties, src/main/resources/application-prod.properties, src/main/resources/application.properties, src/test/java/egovframework/com/ProfileTestDev.java, src/test/java/egovframework/com/ProfileTestProd.java
어플리키에션이 실행되는 환경(개발,운영등)에 따라 서로 다른 구성 요소들의 설정값을 지정하는 Profile을 추가했습니다.
```bash
-spring.profiles.active=prod
```를 지정하지 않으면 dev가 default로 설정됩니다.
=> 어플리케이션 실행 환경(개발,운영)에 따른 profile 적용

src/main/java/egovframework/EgovBootApplication.java, src/main/resources/application.properties
당일 로그 파일명: backend-2023-05-05.log
과거 로그 파일명: backend-2023-05-05.2023-05-05-0.log
당일 로그 파일명: backend.log
과거 로그 파일명: backend-2023-05-05.log
=> 당일 로그, 과거 로그 파일명 에러수정

src/main/java/egovframework/com/cmm/EgovMessageSource.java, src/main/java/egovframework/com/config/EgovConfigAppCommon.java, src/main/java/egovframework/com/config/EgovConfigAppMsg.java, src/test/java/egovframework/com/EgovMessageSourceTest.java
- 기존에는 Locale.getDefault() 으로만 가져왔음
- Locale 직접 입력을 통해 디폴트로 정해진 언어 외 다른 메세지를 가져올 수 있게 기능 개선 - 지역별로 언어가 아닌 접속 아이디별로 언어 설정을 할 필요가 있을것 같아 추가함
- Config분리 및 Test Code 작성
=> EgovMessageSource 기능 개선

.gitignore, src/main/java/egovframework/com/config/EgovConfigAppProperties.java, src/main/java/egovframework/let/cop/bbs/web/EgovBBSAttributeManageApiController.java, src/main/java/egovframework/let/cop/bbs/web/EgovBBSManageApiController.java, src/main/java/egovframework/let/cop/com/web/EgovBBSUseInfoManageApiController.java, src/main/resources/application-dev.properties, src/main/resources/application-prod.properties, src/main/resources/application.properties
- fileStorePath, Page Config 설정 방법 변경 ( application.properties )
=> fileStorePath, Page Config 설정 방법 변경 ( application.properties )

src/main/java/egovframework/com/jwt/config/JwtVerification.java
JWT 검증 시 세션 값 체크 로직은 제외하였습니다.
jjwt 라이브러리에서 payload를 파싱하는 과정에서 내부적으로 처리되는 유효성 검증만으로 충분하다고 판단됩니다.
=> Fix: JWT 검증 로직 수정

src/main/java/egovframework/com/jwt/config/EgovJwtTokenUtil.java, src/main/resources/application.properties, src/main/resources/static/index.html
JWT secret key 설정 방법 변경(application.properties)
index.html 페이지 문구에 key 변경 안내 추가
=> JWT secret key 설정 방법 변경(application.properties)

src/main/java/egovframework/com/cmm/web/EgovFileDownloadController.java, src/main/java/egovframework/com/cmm/web/EgovImageProcessController.java
- [] 버그수정 Bug fixes
기존 파일 처리 시 try문 밖에 input/outputStream을 선언하고 finally에서 close 하는 것에서
자바 1.7 이후 추가된 Try-with-resources 기능으로 대체하였습니다.
해당 기능을 사용할 시 자원 사용 후 자동으로 자원 해제를 해주기 때문에 소스가 간략해지고 기존 로직에서 close의 null 체크 누락으로 인한 오류도 막을 수 있습니다.
- [] JUnit 테스트 JUnit tests
기능 동작을 위해 이미지 처리 전 후로 로그 추가했습니다. …
=> 이미지 처리, 파일 다운로드 Try-with-resources 적용

src/main/java/egovframework/let/uat/uia/web/EgovLoginApiController.java
Swagger에서 API 디스크립션을 달기 위한 Tag 어노테이션은 API 문서화와 관련된 메타데이터를 제공하는 데 사용됩니다. 
이를 통해 개발자는 작성한 API에 대한 추가 정보를 제공하고, 
이 정보는 Swagger UI나 다른 문서화 도구에서 사용되어 시각적으로 표현됩니다.
=> Swagger API Description Sample Annotaion

src/main/java/egovframework/EgovBootApplication.java, src/main/java/egovframework/com/cmm/AltibaseClobStringTypeHandler.java, src/main/java/egovframework/com/cmm/EgovComOthersExcepHndlr.java, src/main/java/egovframework/com/cmm/ResponseCode.java, src/main/java/egovframework/com/cmm/annotation/IncludedInfo.java, src/main/java/egovframework/com/cmm/filter/HTMLTagFilter.java, src/main/java/egovframework/com/cmm/filter/HTMLTagFilterRequestWrapper.java, src/main/java/egovframework/com/cmm/interceptor/AopExceptionTransfer.java, src/main/java/egovframework/com/cmm/service/EgovCmmUseService.java, src/main/java/egovframework/com/cmm/service/EgovUserDetailsService.java, src/main/java/egovframework/com/cmm/service/ResultVO.java, src/main/java/egovframework/com/cmm/web/EgovBindingInitializer.java, src/main/java/egovframework/com/config/EgovConfigApp.java, src/main/java/egovframework/com/config/EgovWebServletContextListener.java, src/main/java/egovframework/com/config/SwaggerConfig.java, src/main/java/egovframework/com/jwt/EgovJwtTokenUtil.java, src/main/java/egovframework/let/utl/fcc/service/EgovNumberUtil.java
=> 주석 없는 파일에 대하여 주석 추가하였습니다.

.gitignore, src/main/java/egovframework/let/uat/esm/web/EgovSiteManagerApiController.java
1. 관리자 암호가 변경되지 않아서 확인해 보니  EgovSiteManagerApiController.java 파일 소스가 변경되어 있었습니다.(초기에 제가 푸시 할 때와 이후 다른 분에 의해 소스가 변경되었습니다.)
2. 전자정부표준프레임워크 개발환경에서 프로젝트를 불러올 때 .factorypath 파일이 자동으로 생성되어서 깃 허브관리에서 제외 시켰습니다.
EgovSiteManagerApiController.java 파일에서 updateAdminPassword()메서드의 파라미터 애노테이션 변경(아래)
@RequestParam 에서 @RequestBody로 변경
리액트에서 보낼 때 body 로 보내기 때문에 백엔드에서 받을 때 @RequestBody 받아야 값이 제대로 들어 옵니다.
테스트 전과 후의 스크린샷 또는 캡처 …
=> 관리자 암호 변경 처리 작동 오류 해결

README.md
스웨거에서 POST,PUT,DELETE 엔드포인트를 사용 하기위해서는 필요한 jwt(토큰)사용하는 방법이 주석으로 있었으면 좋겠다는 생각으로 README.md 에 주석을 추가해 봅니다.
README.md 파일에 "BackEnd 구동 후 확인" 부분에 스웨거 jwt(토큰) 인가(인증)을 사용하여 POST,PUT,DELETE 엔드포인트를 테스트하는 방법을 간단히 요약해 놓았습니다.
인증없이 POST 실행(아래)
인증 후 POST 실행(아래)
=> 스웨거에서 POST,PUT,DELETE 엔드포인트를 사용 하기위해서는 필요한 jwt(토큰)사용하는 방법 주석으로 추가

src/main/java/egovframework/let/uat/esm/web/EgovSiteManagerApiController.java
"/adminPassword" API의 URL 을 최적화 하였고, HTTP Method를 용도에 맞게 POST -> PATCH로 수정하였습니다.
테스트 전과 후의 스크린샷 또는 캡처 영상을 이곳에 첨부해 주세요. Please attach screenshots or video captures of your before and after tests here.
=> "/adminPassword" API,  Method 수정

src/main/java/egovframework/let/cop/bbs/service/impl/BBSManageDAO.java, src/main/java/egovframework/let/cop/bbs/service/impl/EgovBBSManageServiceImpl.java
게시물 관리를 위한 데이터 접근 클래스를 롬복으로 생성자 기반 종속성 주입으로 수정
모든 소스에 @Resource 를 롬복 @RequiredArgsConstructor 로 생성자 기반 종속성 주입으로 수정하려고 합니다.
확인 부탁드립니다.
1. @Repository 를 형식 안전하게 수정
- Typesafe
- 형식 안전
- `@Repository("BBSManageDAO")` 을 `@Repository` 로 수정
- ` *   2024.08.15  이백행          @Repository 를 형식 안전하게 수정` 개정이력 수정
2. 롬복으로 생성자 기반 종속성 주입으로 수정
- Constructor-based Dependency Injection
- 생성자 기반 종속성 주입
- ` *   2024.08.15  이백행          롬복으로 생성자 기반 종속성 주입으로 수정` 개정이력 수정
```java
@Resource(name = "BBSManageDAO")
private BBSManageDAO bbsMngDAO;
```
을
```java
@RequiredArgsConstructor
public class EgovBBSManageServiceImpl …
```
=> 게시물 관리를 위한 데이터 접근 클래스를 롬복으로 생성자 기반 종속성 주입으로 수정

src/main/java/egovframework/let/cop/bbs/service/impl/EgovBBSManageServiceImpl.java, src/main/java/egovframework/let/cop/bbs/web/EgovBBSManageApiController.java, src/main/java/egovframework/let/cop/smt/sim/service/impl/EgovIndvdlSchdulManageServiceImpl.java, src/main/java/egovframework/let/cop/smt/sim/service/impl/IndvdlSchdulManageDao.java, src/main/java/egovframework/let/cop/smt/sim/web/EgovIndvdlSchdulManageApiController.java, src/main/java/egovframework/let/main/web/EgovMainApiController.java
- Constructor-based Dependency Injection
- 생성자 기반 종속성 주입
- ` *   2024.08.26  이백행          컨트리뷰션 롬복 생성자 기반 종속성 주입` 개정이력 수정
---
- `@RequiredArgsConstructor/@Qualifier` 추가
- Constructor-based Dependency Injection
- 생성자 기반 종속성 주입
- https://docs.spring.io/spring-framework/reference/core/beans/dependencies/factory-collaborators.html#beans-constructor-injection
- Spring Beans and Dependency Injection
- 스프링 빈과 종속성 주입
- https://docs.spring.io/spring-boot/reference/using/spring-beans-and-dependency-injection.html
- ` *   2024.08.27  이백행          컨트리뷰션 롬복 생성자 기반 종속성 주입` 개정이력 수정
알림마당 > 오늘의행사
- http://localhost:3000/inform/daily
- …
=> 게시물 관리 롬복 생성자 기반 종속성 주입

src/main/java/egovframework/let/cop/com/service/impl/BBSUseInfoManageDAO.java, src/main/java/egovframework/let/cop/com/service/impl/EgovBBSUseInfoManageServiceImpl.java, src/main/java/egovframework/let/cop/com/web/EgovBBSUseInfoManageApiController.java
- [사이트관리 > 게시판사용관리] 롬복 생성자 기반 종속성 주입
- Constructor-based Dependency Injection
- 생성자 기반 종속성 주입
- https://docs.spring.io/spring-framework/reference/core/beans/dependencies/factory-collaborators.html#beans-constructor-injection
- Spring Beans and Dependency Injection
- 스프링 빈과 종속성 주입
- https://docs.spring.io/spring-boot/reference/using/spring-beans-and-dependency-injection.html
- ` *   2024.08.29  이백행          컨트리뷰션 롬복 생성자 기반 종속성 주입` 개정이력 수정
사이트관리 > 게시판사용관리
- http://localhost:3000/admin/usage
- http://localhost:8080/bbsUseInf?pageIndex=1&searchCnd=0&searchWrd=
```
/bbsUseInf
```
1. …
=> [사이트관리 > 게시판사용관리] 롬복 생성자 기반 종속성 주입

src/main/java/egovframework/let/uat/esm/service/impl/EgovSiteManagerServiceImpl.java, src/main/java/egovframework/let/uat/esm/service/impl/SiteManagerDAO.java, src/main/java/egovframework/let/uat/esm/web/EgovSiteManagerApiController.java
- [사이트관리 > 사이트관리자 암호변경] 롬복 생성자 기반 종속성 주입
- Constructor-based Dependency Injection
- 생성자 기반 종속성 주입
- https://docs.spring.io/spring-framework/reference/core/beans/dependencies/factory-collaborators.html#beans-constructor-injection
- Spring Beans and Dependency Injection
- 스프링 빈과 종속성 주입
- https://docs.spring.io/spring-boot/reference/using/spring-beans-and-dependency-injection.html
- ` *   2024.08.29  이백행          컨트리뷰션 롬복 생성자 기반 종속성 주입` 개정이력 수정
사이트관리 > 사이트관리자 암호변경
- http://localhost:3000/admin/manager/
- http://localhost:8080/admin/password
```
/admin/password
```
1. SiteManagerDAO
```java …
```
=> [사이트관리자 암호변경] 롬복 생성자 기반 종속성 주입

pom.xml, src/test/java/egovframework/let/uat/uia/web/TestEgovLoginApiControllerSelenium.java, src/test/resources/logback-spring.xml
- src/test/java 추가
- src/test/resources 추가
- Selenium 라이브러리 설치
- 셀레늄 단위 테스트 추가
1. 브랜치 생성
http://localhost:3000/login
http://localhost:8080/auth/login-jwt
```
/auth/login-jwt
```
```
2024/selenium/EgovLoginApiController
```
2. 셀레늄 단위 테스트 추가
```
egovframework.let.uat.uia.web
```
```
TestSelenium
TestEgovLoginApiControllerSelenium
```
/egovframe-template-simple-backend/pom.xml
```xml
<selenium.version>4.23.1</selenium.version>
</properties>
<dependency>
<groupId>org.seleniumhq.selenium</groupId>
<artifactId>selenium-java</artifactId>
<scope>test</scope>
</dependency>
</dependencies>
```
3. Selenium …
=> [2024년 전자정부 표준프레임워크 컨트리뷰션][로그인] 셀레늄 단위 테스트

src/main/java/egovframework/com/cmm/EgovComponentChecker.java, src/main/java/egovframework/com/cmm/service/impl/EgovFileMngServiceImpl.java, src/main/java/egovframework/com/cmm/service/impl/FileManageDAO.java, src/main/java/egovframework/com/cmm/web/EgovFileDownloadController.java, src/main/java/egovframework/com/cmm/web/EgovFileMngApiController.java, src/main/java/egovframework/com/cmm/web/EgovImageProcessController.java, src/main/java/egovframework/com/sns/SnsLoginApiController.java, src/main/java/egovframework/let/cop/com/service/impl/EgovUserInfManageDAO.java, src/main/java/egovframework/let/cop/com/service/impl/EgovUserInfManageServiceImpl.java, src/main/java/egovframework/let/uat/uia/service/impl/EgovLoginServiceImpl.java, src/main/java/egovframework/let/uat/uia/service/impl/LoginDAO.java, src/main/java/egovframework/let/uat/uia/web/EgovLoginApiController.java
[2024년 전자정부 표준프레임워크 컨트리뷰션][심플홈페이지 BackEnd][게시판사용관리] 롬복 생성자 기반 종속성 주입
- `@Repository("DAO")` 를 `@Repository` 로 수정
- `@Service("Service")` 를 `@Service` 로 수정
- SnsLoginApiController.loginService 필드의 값이 사용되지 않아 제거
- EgovLoginApiController.propertiesService 필드의 값이 사용되지 않아 제거
- EgovLoginApiController.leaveaTrace 필드의 값은 사용되지 않아 제거
- ` *   2024.09.20  이백행          컨트리뷰션 롬복 생성자 기반 종속성 주입` 개정이력 수정
크롬 링크 주소 복사
```
http://localhost:8080/bbsUseInf?pageIndex=1&searchCnd=0&searchWrd=
```
검색
```
/bbsUseInf
```
브랜치 생성
```
2024/di/EgovUserInfManageDAO
```
`@Repository` DAO
```java …
```
=> [게시판사용관리] 롬복 생성자 기반 종속성 주입

src/main/java/egovframework/let/uss/umt/service/impl/EgovMberManageServiceImpl.java, src/main/java/egovframework/let/uss/umt/service/impl/MberManageDAO.java, src/main/java/egovframework/let/uss/umt/web/EgovMberManageApiController.java
[회원관리] 롬복 생성자 기반 종속성 주입
- `@Repository("DAO")` 를 `@Repository` 로 수정
- `@Service("Service")` 를 `@Service` 로 수정
- idgenService 를 egovUsrCnfrmIdGnrService 로 이름 바꾸기
- `@SuppressWarnings("unchecked")` 제거
- EgovMberManageApiController.egovMessageSource 필드의 값은 사용되지 않아 제거
- ` *   2024.09.20  강동휘          컨트리뷰션 롬복 생성자 기반 종속성 주입` 개정이력 수정
크롬 링크 주소 복사
```
http://localhost:8080/members?pageIndex=1&searchCnd=0&searchWrd=
```
검색
```
/members
```
브랜치 생성
```
2024/di/EgovMberManageApiController
```
`@Repository` DAO
```java
```
`@Repository` DAO
```java
//@Repository("mberManageDAO") …
```
=> [회원관리] 롬복 생성자 기반 종속성 주입

src/main/java/egovframework/let/cop/bbs/service/impl/BBSAddedOptionsDAO.java, src/main/java/egovframework/let/cop/bbs/service/impl/BBSLoneMasterDAO.java, src/main/java/egovframework/let/cop/bbs/service/impl/EgovBBSLoneMasterServiceImpl.java, src/main/java/egovframework/let/cop/com/web/EgovBBSUseInfoManageApiController.java
- `@Repository("DAO")`를 `@Repository`로 수정
- `@Service("Service")`를 `@Service`로 수정
- idgenService 를 egovBBSMstrIdGnrService 로 이름 바꾸기
크롬 링크 주소 복사
- [게시판 속성 조회 스웨거 바로 가기](http://localhost:8080/swagger-ui/index.html#/EgovBBSAttributeManageApiController/selectBBSMasterInf)
검색 키워드
```
/board
```
브랜치 이름
```
2024/di/BBSAddedOptionsDAO
```
`@Repository` DAO 2단계 기능 추가 (댓글관리, 만족도조사) 관리를 위한 데이터 접근 클래스
```java
//@Repository("BBSAddedOptionsDAO")
@Repository
public class BBSAddedOptionsDAO extends EgovAbstractMapper {
```
`@Repository` DAO 게시판 속성정보 관리를 위한 데이터 접근 클래스 - **사용하지 않으면 삭제 …
=> [게시판 속성 관리] 롬복 생성자 기반 종속성 주입

src/main/java/egovframework/com/cmm/service/IntermediateResultVO.java, src/main/java/egovframework/let/cop/bbs/domain/request/BbsSearchRequestDTO.java, src/main/java/egovframework/let/cop/bbs/domain/response/BbsListResponseVO.java, src/main/java/egovframework/let/cop/bbs/domain/response/BbsResponseVO.java, src/main/java/egovframework/let/cop/bbs/service/EgovBBSAttributeManageService.java, src/main/java/egovframework/let/cop/bbs/service/impl/EgovBBSAttributeManageServiceImpl.java, src/main/java/egovframework/let/cop/bbs/web/EgovBBSAttributeManageApiController.java, src/main/java/egovframework/let/cop/bbs/web/EgovBBSManageApiController.java
**EgovBBSAttributeManageApiController 컨트롤러의 selectBBSMasterInfs 메서드 기반 코드 정리 및 아래 내용 적용**
- 기존 Map<String, Object> 기반 응답 제거
- IntermediateResultVO<T> 도입으로 DTO 기반 응답 표준화 (추후 모두 반영 시 ResultVO로 변경 및 ResultVoHelper 제거 예정)
- BbsListResponseVO 생성 및 적용 (resultList, resultCnt, pagination, resultCode, resultMessage)
- IntermediateResultVO의 필드를 자동으로 채워주는 success() 메서드 구현
- Swagger 문서에서 응답 구조가 출력 되지 않던 문제 해결 → `result` 기준으로 명확하게 표현됨
요청/응답 객체를 나누는 방향으로 감으로써 역할 구분이 명확해지며 스웨거 문서 자동화 및 유지 보수, 타입 안정성, 테스트가 용이해지는 효과를 기대할 수 있다고 봅니다. 현재는 모든 요청을 VO로 받기에 어떠한 요청이 들어왔는지 확인하려면 toString으로 하나하나 값을 찾아가야하며, 응답도 마찬가지로 Map에 모든 데이터를 담음으로써 코드를 추적하고 …
=> Refactor(EgovBBSAttributeManageApiController) : 요청/응답 구조 개선

src/main/java/egovframework/let/cop/bbs/controller/EgovBBSAttributeManageApiController.java, src/main/java/egovframework/let/cop/bbs/controller/EgovBBSManageApiController.java, src/main/java/egovframework/let/cop/bbs/dto/request/BbsManageDeleteBoardRequestDTO.java, src/main/java/egovframework/let/cop/bbs/dto/request/BbsSearchRequestDTO.java, src/main/java/egovframework/let/cop/bbs/dto/response/BbsAttributeDetailResponseDTO.java, src/main/java/egovframework/let/cop/bbs/dto/response/BbsDetailResponse.java, src/main/java/egovframework/let/cop/bbs/dto/response/BbsManageFileAtchResponseDTO.java, src/main/java/egovframework/let/cop/bbs/enums/BbsDetailRequestType.java, src/main/java/egovframework/let/cop/bbs/service/EgovBBSAttributeManageService.java, src/main/java/egovframework/let/cop/bbs/service/EgovBBSManageService.java, src/main/java/egovframework/let/cop/bbs/service/impl/EgovBBSAttributeManageServiceImpl.java, src/main/java/egovframework/let/cop/bbs/service/impl/EgovBBSManageServiceImpl.java, src/main/java/egovframework/let/cop/com/web/EgovBBSUseInfoManageApiController.java, src/main/java/egovframework/let/uss/umt/web/EgovMberManageApiController.java, src/test/java/egovframework/let/cop/bbs/service/impl/EgovBBSUseInfoManageServiceImplTestInsertBBSMastetInfTest.java
아래 구조 개선으로 인해 응답 구조가 변경되었으며 리액트 코드가 일부 수정되었습니다.
프론트 PR : [eGovFramework/egovframe-template-simple-react#69](https://github.com/eGovFramework/egovframe-template-simple-react/pull/69)
<br>
**1. selectUserBBSMasterInf() 불필요 코드 제거**
- 응답 구조 개선으로 인한 HashMap 등 불필요 코드 제거
<br>
**1. Swagger 문서 예시 누락 문제 해결**
- BbsAttributeDetailResponseDTO 등의 DTO 필드에 @Schema(example = "...") 추가
- 예시값 미지정으로 Swagger 요청/응답 예시가 비어 있는 문제를 해결
<br>
**2. 응답 명세 명확화**
- selectBBSMasterInf 응답 스키마에 @Schema(oneOf = {...}), @ApiResponse, @content 등을 명시
- Swagger 문서에서 실제 반환 타입이 명확히 보이도록 개선
<br>
**3. 네이밍 리팩토링**
- 공통 요청 DTO 명확화를 위해 Attribute, Manage 관련 DTO 네이밍 통일
- 예) BbsAttributeSearchRequestDTO→ BbsSearchRequestDTO 등 (Attribute와 Manage에서 공동 사용 되므로)
<br>
**4. 응답 구조 및 타입 표준화**
- BbsAttributeDetailResponseDTO, …
=> Refactor(bbs): 게시판 마스터 상세 내용(파일첨부) 조회 메서드 Swagger 문서 보완 및 API 응답 구조 리팩토링

src/main/java/egovframework/com/cmm/service/EgovProperties.java
테스트 전과 후의 스크린샷 또는 캡처 영상을 이곳에 첨부해 주세요. Please attach screenshots or video captures of your before and after tests here.
=> [chore] 불필요한 주석 처리 제거

swagger.md
- **Swagger 사용방법 가이드 문서** (`swagger-guide.md`) 신규 작성
- eGov Framework Simple Backend 템플릿에서 Swagger UI를 효과적으로 사용할 수 있도록 상세한 가이드 제공
1. **Swagger UI 접속 방법** - 기본 설정 및 접속 확인 절차
2. **JWT 토큰 인증 설정** - 단계별 인증 과정 상세 설명
- 로그인 API 호출 (`/auth/login-jwt`)
- 토큰 복사 및 설정 방법
3. **API 테스트 방법** - GET/POST/PUT/DELETE 요청별 테스트 절차
4. **응답 코드 이해** - 성공/오류 응답 코드 설명
5. **실제 사용 예시** - 게시판 API를 활용한 구체적인 예시
6. **문제 해결 가이드** - 일반적인 오류 상황별 해결 방법
- 개발자들이 Swagger UI를 처음 사용할 때 겪는 어려움 해소
- JWT 인증 과정에 대한 명확한 이해 제공
- API 테스트 효율성 향상
*참고: 문서 추가로 인한 변경사항으로 JUnit 테스트는 …
=> Swagger 사용방법 가이드 신규 작성
